blueprint:
  name: "Air Filter Replacement Reminder"
  description: |
    Automated air filter replacement monitoring with intelligent notifications.
    
    **Features:**
    - Monitor multiple air filter lifetime sensors
    - Configurable replacement threshold
    
    **Usage Notes:**
    - Recommended replacement threshold: 10-20% remaining life
    - Works with HVAC systems, air purifiers, and standalone filters
  domain: automation
  author: "William Bartholomew"
  homeassistant:
    min_version: "2024.6.0"
  input:
    # Main Configuration Section
    main_config:
      name: "Main Configuration"
      icon: "mdi:air-filter"
      description: "Primary air filter monitoring configuration"
      input:
        filter_lifetime_sensors:
          name: "Filter Lifetime Sensors"
          description: "Select the air filter sensors to monitor for replacement needs"
          selector:
            entity:
              multiple: true
              filter:
                domain: sensor
        
        location_prefix:
          name: "Location Prefix"
          description: "Optional prefix for filter location (e.g., 'HVAC', 'Bedroom Air Purifier')"
          default: "Air Filter"
          selector:
            text:
    
    # Threshold Configuration Section
    threshold_config:
      name: "Threshold Configuration"
      icon: "mdi:tune"
      description: "Customize replacement alert thresholds"
      input:
        filter_replace_threshold:
          name: "Replacement Threshold"
          description: "Filter life percentage at which to trigger replacement notifications"
          default: 15
          selector:
            number:
              min: 5
              max: 50
              step: 5
              unit_of_measurement: "%"
              mode: slider

    # Notification Settings Section
    notification_config:
      name: "Notification Settings"
      icon: "mdi:bell-alert"
      description: "Configure notification delivery and behavior"
      input:
        notification_service:
          name: "Notification Service"
          description: "Select the notification service to send alerts to"
          default: "notify.persistent_notification"
          selector:
            select:
              custom_value: true
              options:
                - "notify.notify"
                - "notify.mobile_app"
                - "notify.persistent_notification"

    # Notification Content Section
    notification_content_config:
      name: "Customize Notification Content (Optional)"
      icon: "mdi:message-text"
      description: "Customize notification titles and messages"
      collapsed: true
      input:
        notification_title:
          name: "Notification Title"
          description: "Custom title for replacement notifications"
          default: "🔧 Air Filter Replacement Required"
          selector:
            text:
        
        notification_message:
          name: "Notification Message"
          description: |
            Custom message template for replacement alerts. Available variables:
            - `{location}`: Location prefix
            - `{entity}`: Filter sensor entity name
            - `{friendly_name}`: Friendly name of the sensor
            - `{percentage}`: Remaining life percentage
          default: "{location} \"{friendly_name}\" needs replacement ({percentage}% remaining)"
          selector:
            text:
              multiline: true

variables:
  filter_sensors: !input filter_lifetime_sensors
  replace_threshold: !input filter_replace_threshold
  location_prefix: !input location_prefix
  notification_service: !input notification_service
  notification_title: !input notification_title
  notification_message: !input notification_message

trigger:
  - platform: numeric_state
    entity_id: !input filter_lifetime_sensors
    below: !input filter_replace_threshold
    id: "filter_needs_replacement"

condition: []

action:
  # Send notification
  - service: "{{ notification_service }}"
    data:
      title: "{{ notification_title }}"
      message: >-
        {{ notification_message.replace('{location}', location_prefix)
                             .replace('{entity}', trigger.to_state.entity_id)
                             .replace('{friendly_name}', trigger.to_state.attributes.friendly_name or trigger.to_state.entity_id)
                             .replace('{percentage}', trigger.to_state.state) }}
      data:
        tag: "air_filter_{{ trigger.to_state.entity_id | replace('.', '_') }}"
